version: '3.6'

volumes:
  srv-bookstack-db-volume:
    external: true
  srv-bookstack-volume:
    external: true
  srv-openproject-pgdata-volume:
    external: true
  srv-openproject-assets-volume:
    external: true
  srv-gitlab-volume-logs:
    external: true
  srv-gitlab-volume-opt:
    external: true
  srv-gitlab-volume-etc:
    external: true

networks:
  net-lab:
    name: net-lab-${NET_LAB_SUBNET}
    external: true

services:

  srv-excalidraw:
    image: excalidraw/excalidraw:sha-4bfc5bb
    container_name: 'srv-excalidraw'
    restart: unless-stopped
    networks:
      net-lab:
        ipv4_address: ${NET_SRVICES_EXCALIDRAW_IP}

  srv-bookstack-db:
    image: lscr.io/linuxserver/mariadb:10.6.10
    container_name: 'srv-bookstack-db'
    restart: unless-stopped
    networks:
      net-lab:
        ipv4_address: ${NET_SRVICES_BOOKSTACK_DB_IP}
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=bookstack
      - TZ=Europe/Rome
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstack
    volumes:
      - srv-bookstack-db-volume:/config

  srv-bookstack:
    image: lscr.io/linuxserver/bookstack:22.10.2
    container_name: 'srv-bookstack'
    restart: unless-stopped
    networks:
      net-lab:
        ipv4_address: ${NET_SRVICES_BOOKSTACK_IP}
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://srv-bookstack/
      - DB_HOST=${NET_SRVICES_BOOKSTACK_DB_IP}
      - DB_USER=bookstack
      - DB_PASS=bookstack
      - DB_DATABASE=bookstackapp
    volumes:
      - srv-bookstack-volume:/config
    depends_on:
      - srv-bookstack-db

  srv-openproject:
    image: openproject/community:12
    container_name: srv-openproject
    restart: unless-stopped
    networks:
      net-lab:
        ipv4_address: ${NET_SRVICES_OPENPROJECT_IP}
    environment:
      - OPENPROJECT_HOST__NAME=srv-openproject
      - OPENPROJECT_HTTPS=false
    volumes:
      - srv-openproject-pgdata-volume:/var/openproject/pgdata
      - srv-openproject-assets-volume:/var/openproject/assets

  srv-gitlab:
    image: 'gitlab/gitlab-ce:15.4.2-ce.0'
    container_name: 'srv-gitlab'
    restart: unless-stopped
    networks:
      net-lab:
        ipv4_address: ${NET_SRVICES_GITLAB_IP}
    volumes:
      - srv-gitlab-volume-logs:/var/log/gitlab
      - srv-gitlab-volume-opt:/var/opt/gitlab
      - srv-gitlab-volume-etc:/etc/gitlab
    environment:
      GIT_CURL_VERBOSE: 1
      GIT_TRACE: 1
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://srv-gitlab'
    hostname: srv-gitlab
    shm_size: '256m'
