version: '3.6'

networks:

  net-lab:
    name: net-lab-${NET_LAB_SUBNET}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NET_LAB_SUBNET}
          gateway: ${NET_LAB_GATEWAY}

services:

  net-gateway-lab:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: net-gateway-lab
    restart: unless-stopped
    networks:
      net-lab:
        ipv4_address: ${NET_GATEWAY_LAB_IP}
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${NET_GATEWAY_LAB_MOUNT_VOLUME_DATA}/data:/data
      - ${NET_GATEWAY_LAB_MOUNT_VOLUME_LETSENCRYPT}/letsencrypt:/etc/letsencrypt